ALTER TABLE users
ALTER COLUMN id SET NOT NULL;

ALTER TABLE users
ALTER COLUMN login SET NOT NULL;

ALTER TABLE users
ADD CONSTRAINT unique_login UNIQUE (login);

ALTER TABLE users
ALTER COLUMN password SET NOT NULL;

ALTER TABLE users
ALTER COLUMN record SET NOT NULL;
